[package]
  name = "miso"
  version = "0.1.0"
  edition = "2021"

  [lib]
  name = "miso"
  crate-type = ["cdylib", "rlib"]

  [dependencies]
  pyo3 = { version = "0.21", features = ["extension-module"] }
  anyhow = "1"
  thiserror = "1"

  [features]
  default = []