[build-system]
  requires = ["maturin>=1.5,<2.0"]
  build-backend = "maturin"

  [project]
  name = "miso"
  version = "0.1.0"
  requires-python = ">=3.9"

  [tool.maturin]
  python-packages = ["python/miso"]